### ISSUE TITLE
Unable to initialize libchewing: dictionary.dat

### ISSUE THREAD

**Issue by ShamrockLee** [hiroshiyui/GuilelessBopomofo#13]
**Describe the bug**
*   Error message:
    ```
    無法成功初始化新酷音程式庫：dictionary.dat
    ```
    pops up during the first time the keyboard is used.
*   The keyboard shows only QWERTY alphabets on the keys and outputs nothing.

**To Reproduce**
1.  Install from F-Droid
2.  Activate the keyboard from the setting through the button in the app
3.  Open a text editor or anything you can type on
4.  Switch to this keyboard
5.  See error

**Expected behavior**
The keyboard shows bopomofo symbols and outputs Chinese phrases

**Screenshots**
![195190_llcrop](https://user-images.githubusercontent.com/44064051/125870259-965eecd2-f98a-44e1-afce-d478f76eb0a7.jpg)

**Smartphone (please complete the following information):**
 - Device: OPPO Reno
 - OS: Android 10 (ColorOS 7.1)
 - Version: 1.3.5

**Comment by hiroshiyui** [comment]
@ShamrockLee I apologize for any inconvenience caused to you, it seems like there is something wrong in F-Droid build process, would you mind if I ask you to install APK from [here](https://github.com/hiroshiyui/GuilelessBopomofo/releases/tag/1.3.5) to see if it works as expected?

**Comment by ShamrockLee** [comment]
@hiroshiyui Thanks a lot!
I'll try that and see if it works.

**Comment by ShamrockLee** [comment]
It works!

Thank you for this great project! It's the very keyboard I'm looking over the years.

**Comment by hiroshiyui** [comment]
From release 1.3.6 in F-Droid, I have been verified that `dictionary.dat` & `index_tree.dat` are being built as expected. Thank you @ShamrockLee for reporting the issue.
