### ISSUE TITLE
[Feature request] An option to disable haptic feedback

### ISSUE THREAD

**Issue by Leo123457** [hiroshiyui/GuilelessBopomofo#15]
如同標題描述，現在只能調整振動的強弱
希望可以有完全關閉振動的選項
![Screenshot_20210802-194349560](https://user-images.githubusercontent.com/75062444/127856742-39886497-2429-4050-ab5e-bf110b133211.jpg)

謝謝您製作這個輸入法！

**Comment by hiroshiyui** [comment]
@Leo123457 Done in release 1.4.0, enjoy!
