### ISSUE TITLE
F-Droid build failed: Clean depends on prepareChewing

### ISSUE THREAD

**Issue by linsui** [hiroshiyui/GuilelessBopomofo#16]
fdroidserver run gradle clean before scan. The clean task depends on prepareChewing which build some binaries so that we got

```
2021-08-09 10:12:56,559 ERROR: Found binary at app/libs/libchewing/src/tools/dump_database
2021-08-09 10:12:56,559 ERROR: Found binary at app/libs/libchewing/src/tools/init_database
```

We can just remove them but I thought this is a bug. What do you think? Will you change that or we should just remove them? Thanks!

**Comment by hiroshiyui** [comment]
@linsui I will try to fix it later, and I must say thank you and apologize for any inconvenience caused.

**Comment by linsui** [comment]
Thanks!

**Comment by hiroshiyui** [comment]
@linsui Release 1.4.1 should do the correct related cleaning tasks while running `gradle clean`, if the issue still occurs, please don't hesitate to let me know, thanks!

**Comment by linsui** [comment]
It builds fine. Thanks!
