### ISSUE TITLE
Suggestion: move the globe button elsewhere on the DaChen keyboard layout

### ISSUE THREAD

**Issue by ltlnx** [hiroshiyui/GuilelessBopomofo#24]
Hello,

After extensive usage of the keyboard (thank you so much!), I have a recurring problem: when I try to type in the DaChen keyboard layout, I often hit the globe button by accident, and it would switch to other keyboards. Would it be possible to move the globe button's functionality elsewhere (perhaps a long press on the abc button?) on the Dachen layout?

Cheers,
ltlnx

**Comment by hiroshiyui** [comment]
![Screenshot_20220907-105848](https://user-images.githubusercontent.com/620662/188778995-ac36d19f-07ab-433b-a8df-1c0e35848a9c.png)

You may try to enable this option in case you might hit the button accidently.

**Comment by ShamrockLee** [comment]
@hiroshiyui Trying to enable the option causes the app to crash immediately.

**Comment by ShamrockLee** [comment]
@hiroshiyui 

![image_392579_llcrop.jpg](https://user-images.githubusercontent.com/44064051/188895934-2724d89b-0a04-41cc-a602-417d594efcce.jpg)
![image_392580_llcrop.jpg](https://user-images.githubusercontent.com/44064051/188895984-1bff3f95-68f8-4c96-9944-2aeef2754161.jpg)

**Comment by hiroshiyui** [comment]
@ShamrockLee Oops, my development device is Android 11 too, would you mind to install the debug build APK to give me logs?

**Comment by ShamrockLee** [comment]
> would you mind to install the debug build APK to give me logs?

Sure!

BTW, this behavior is not reproducible on Volla OS (AOSP-based OS without GSF). The version info is as follows:

![croppedImage.png](https://user-images.githubusercontent.com/44064051/188902909-f35f44a6-d29c-419c-b3f0-2d0bca869adb.png)

**Comment by ShamrockLee** [comment]
@hiroshiyui I cannot reproduce the above behavior on version 1.9.0. It seems fixed in this update.

**Comment by ltlnx** [comment]
Hello,
The setting does ease the problem, thanks a lot! Marking this as closed.

Cheers, 
ltlnx
