### ISSUE TITLE
Option to disable vibration

### ISSUE THREAD

**Issue by wonderfulhair** [hiroshiyui/GuilelessBopomofo#26]
Please close if it's just me missing this in basic Android settings, but so far I have found no way to disable vibration when touching keys. Can not find an option for this in the settings for GuilelessBopomofo. Is it a planned feature to add disable vibration or it's already possible and it's just me who can't find it. Other keyboards I'm using on the device are vibration free, which makes me think this related to this keyboard itself.

**Comment by hiroshiyui** [comment]
![Screenshot_20221128-214701~2](https://user-images.githubusercontent.com/620662/204293823-6cc62712-e740-457a-a8d1-2d9a1b52982f.png)

**Comment by wonderfulhair** [comment]
Fantastic, thank you.

And thanks for making this input method. :+1:
