### ISSUE TITLE
[Feature Request] Themed / Monochrome app icon support

### ISSUE THREAD

**Issue by sebastien46** [hiroshiyui/GuilelessBopomofo#29]
**Is your feature request related to a problem? Please describe.**

Launcher app icon does not follow user theming in Android 13 & up

**Describe the solution you'd like**

Implement themed app icon

**Describe alternatives you've considered**

None

**Additional context**

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive

**Comment by hiroshiyui** [comment]
![DSC_2844](https://github.com/hiroshiyui/GuilelessBopomofo/assets/620662/6401eab6-4920-4ced-972b-679c83ee22bd)

The App icon design resembles my first, yellowed keyboard, I don't want to change it.
