### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [hiroshiyui/GuilelessBopomofo#3]
You can add Screenshots for F-Droid, too, if you want. https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/ https://gitlab.com/snippets/1895688 That was simply information about what is still possible. You would then only have to enter the screenshots in fastlane.

**Comment by hiroshiyui** [comment]
@mondlicht-und-sterne Thanks. Actually there are here https://github.com/hiroshiyui/GuilelessBopomofo/tree/master/fastlane/metadata/android/zh-TW/images just seems like F-Droid have to add images per locale, I will add them later.

**Comment by hiroshiyui** [comment]
@mondlicht-und-sterne https://f-droid.org/en/packages/org.ghostsinthelab.apps.guilelessbopomofo/ Looks like there are screenshots in English page now. Thanks for your feedback!

**Comment by mondlicht-und-sterne** [comment]
@hiroshiyui Thank you
