### ISSUE TITLE
希望在未來的版本中加入的功能

### ISSUE THREAD

**Issue by pea-snow** [hiroshiyui/GuilelessBopomofo#32]
在當前版本(1.9.44)的軟體中，實體鍵盤模式仍只能通過在設定中手動開啟
希望在未來的版本中能夠自動識別實體鍵盤並由此決定是否顯示螢幕鍵盤

**Comment by hiroshiyui** [comment]
有沒有一種可能，是有人使用實體鍵盤的時候，也想要保留螢幕鍵盤？

**Comment by pea-snow** [comment]
可以考慮實現為在設定中自行決定連接實體鍵盤時螢幕鍵盤是否要自動收起
而且Android預設的實體鍵盤設定已經有了是否在連接實體鍵盤後仍顯示螢幕鍵盤的選項（但我不知道其他廠商是否可能已將此設定項移除）

**Comment by hiroshiyui** [comment]
所 以 我 不 就 提 供 選 項 了 嗎 ？
