### ISSUE TITLE
[Feature Request] Height adjustment

### ISSUE THREAD

**Issue by ltlnx** [hiroshiyui/GuilelessBopomofo#4]
Hello,
Great app! Is it possible that you add height adjustment abilities to the keyboard? Would love to see it, for it's acquiring almost 70% of my screen.

Regards, 
litelinux

**Comment by hiroshiyui** [comment]
@ltlnx Would you please provide me some screenshots? Or just tell me your device model, then I will have sufficient references to make adjustments to improve your user experience.

**Comment by ltlnx** [comment]
![Screenshot_20210109-122941_瀏覽器](https://user-images.githubusercontent.com/52026741/104083136-17dedf00-5277-11eb-882f-6bef2f99d0d3.png)
![Screenshot_20210109-123618_Firefox](https://user-images.githubusercontent.com/52026741/104083162-62f8f200-5277-11eb-90df-cd21c76893c6.png)
There you go.
My device is a Sony Xperia Z5 Compact, with a 4.6" screen. The height is OK on 許氏 and倚天26, but too high on Zhuyin and English typing.

BTW, Chrome Webview doesn't seem to recognise this app as a keyboard, for the text input area is always under the keyboard, rather than floating up like other keyboards.

**Comment by hiroshiyui** [comment]
@ltlnx Thanks for these useful information, I will do some adjustments for varient screen sizes later.

**Comment by hiroshiyui** [comment]
NOTE: [Sony Xperia Z5 Compact Spec](https://www.gsmarena.com/sony_xperia_z5_compact-7535.php)

The screen resolution makes it too difficult to utilize Guileless Bopomofo, even on portrait orientation.

**Comment by ltlnx** [comment]
![Screenshot_20210109-183540_Firefox](https://user-images.githubusercontent.com/52026741/104089391-8f2d6680-52a9-11eb-8828-b58ab21c643f.png)
Google's solution, as a reference.

**Comment by hiroshiyui** [comment]
@ltlnx From release 1.1.5, the keyboard layout becomes shorter, and it provides an option "Enable fullscreen when in portrait". Please give it a try.

**Comment by ltlnx** [comment]
![Screenshot_20210111-080628_Firefox](https://user-images.githubusercontent.com/52026741/104139095-fea77100-53e3-11eb-8653-4ba1499806c4.png)
Works as expected. Would it affect devices with a bigger screen?

**Comment by hiroshiyui** [comment]
@ltlnx Yes, but not so obviously.

**Comment by hiroshiyui** [comment]
@ltlnx I am going to close this issue, if any issues there about the height of keyboard layout, please re-open this or create a new one. Thanks!
