### ISSUE TITLE
Add screenshots to F-droid

### ISSUE THREAD

**Issue by aha999** [hiroshiyui/GuilelessBopomofo#5]
Currently there's no screenshot on F-Droid for your app.
Please add them.

**Comment by hiroshiyui** [comment]
duplicated of #3

**Comment by hiroshiyui** [comment]
@aha999 https://f-droid.org/en/packages/org.ghostsinthelab.apps.guilelessbopomofo/ Looks like there are screenshots in English page now. Thanks for your feedback!
